// Package v2 GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package v2

import "github.com/swaggo/swag"

const docTemplateV2 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfoV2 holds exported Swagger Info so clients can modify it
var SwaggerInfoV2 = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "V2",
	SwaggerTemplate:  docTemplateV2,
}

func init() {
	swag.Register(SwaggerInfoV2.InstanceName(), SwaggerInfoV2)
}
